rvm:
  - 1.9.3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "bunlde exec rake specsever"
  - "sleep 5"
script: phantomjs assets/vendor/script.coffee http://localhost:5000